#!/bin/bash

set -x

# Openshift default mvn command is SICK as it reset its JAVA_HOME, even after you set ur own JAVA_HOME
if [ ! -d $OPENSHIFT_DATA_DIR/maven ]
        then
                cd $OPENSHIFT_DATA_DIR
                ln -s /usr/share/java/apache-maven-3.0.4 maven
fi

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

# Luckily, JDK8 can be linked since 2015
if [ ! -d $OPENSHIFT_DATA_DIR/jdk8 ]
        then
        		ln -s /usr/lib/jvm/java-1.8.0 jdk8
fi

cd $OPENSHIFT_REPO_DIR
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk8
export PATH=$JAVA_HOME/bin:$OPENSHIFT_DATA_DIR/maven/bin:$PATH
java -version
mvn -version
mvn -s .openshift/settings.xml clean install
